import { type NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '~/Components/AboutMe'
import Banner from '~/Components/Banner'
import Navbar from '~/Components/Navbar'
import SocialMedia from '~/Components/SocialMedia'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className="">

            <Banner />
            <SocialMedia />
            <AboutMe />
            </main>
        </>
    )
}

export default Home
